---
output:
  github_document:
    html_preview: false
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
options(tibble.print_min = 5, tibble.print_max = 5)
```

## tidyfec

The tidyfec package aims to make campaign finance data more accessible in R and friendly with tidy workflows. It works by accessing data through the [OpenFEC API](https://api.open.fec.gov/developers/), which requires an [API key](https://api.data.gov/signup/) to run.

## Installation

Though I'm developing out in the open, this is very much pre-alpha release status. Installation is through the devtools package

```{r, eval = FALSE}
install.packages("devtools")
devtools::install_github("stephenholzman/tidyfec")
```

## Examples

```{r, message = FALSE, warning = FALSE}
library(tidyfec)
library(tidyverse)

#data_gov_api_key("api-key-string")
#install api key

df <- search_candidates(state = "VA", district = "10", office = "H", election_year = "2018") %>%
  get_candidate_totals() %>%
  filter(type_of_funds %in% tidyfec_filters$top_level, cycle == "2018") %>%
  separate(name, c('last_name', 'first_name'), sep = ', ', extra = "drop", fill = "right")

df  %>%
  ggplot() +
  geom_bar(aes(x = last_name, y = amount), stat = "identity") +
  facet_wrap(~type_of_funds) +
  scale_y_continuous(labels = scales::dollar) +
  coord_flip() +
  theme_bw()

```
